books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    
    path('',views.index,name='index'),
    path('<int:pk>/',views.show,name='show'),
    path('add/',views.add ,name='add'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('<int:pk>/delete/',views.delete,name='delete'),
]

web_1210/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

# from . import views


# def root(request):
#     return redirect('books-index')
# 同等於30行第二格

admin.site.site_title = 'Book 網站管理'
admin.site.site_header = 'Book 管理'

urlpatterns = [
    
    path('',lambda request: redirect('books:index'),name='root'),
    path('books/',include('books.urls')),
    path('jet/',include('jet.urls','jet')),
    path('admin/', admin.site.urls),
]

books/models.py
from django.db import models

class Book(models.Model):
    name = models.CharField('書名',max_length = 20)
    price = models.PositiveIntegerField('價格')
    introduction = models.TextField('介紹')

    def __str__(self):
        return self.name

books/forms.py
from django import forms
from .models import Book

# class BookForm(forms.Form):
#     name = forms.CharField(max_length=20 ,label = '書名')
#     price = forms.IntegerField(min_value=1 ,label = '價錢')
#     introduction = forms.CharField(widget = forms.Textarea() ,label = '介紹')

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class DeleteConfirmForm(forms.Form):
    check = forms.BooleanField(label='確定刪除?')

books/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Book
from .forms import BookForm, DeleteConfirmForm
from django.contrib import messages
# from django.http import Http404

def index(request):
    books = Book.objects.all()
    return render(request,'books/index.html',{'books':books})

def show(request,pk):
    # try:
    #     book = Book.objects.get(pk=pk)
    # except:
    #     raise Http404
    book=get_object_or_404(Book,pk=pk)
    return render(request,'books/show.html',{'book':book})

def add(request):
    # form = None
    # if request.method == 'POST':
        
    #     form = BookForm(request.POST)
        
    #     if form.is_valid():
    #         Book.objects.create(**form.cleaned_data)
    # else :
    #     form = BookForm()
            
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,'新增成功')
        return redirect('books:index')

    return render(request,'books/add.html',{'form':form})

def edit(request,pk):
    book=get_object_or_404(Book,pk=pk)        
    form = BookForm(request.POST or None,instance=book)
    if form.is_valid():
        form.save()
        messages.success(request,'更新成功')
        return redirect('books:index')

    return render(request,'books/edit.html',{'form':form})

def delete(request,pk):
    book=get_object_or_404(Book,pk=pk)
    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['check']:
        book.delete()
        messages.success(request,'刪除成功')
        return redirect('books:index')

    return render(request,'books/delete.html',{'form':form})

web_1210/views.py
from django.http import HttpResponse
from django.shortcuts import render

def root(request):
    name=request.GET.get('name','guest')
    return HttpResponse('Hi,{}'.format(name))

def hello(request,name):
    return HttpResponse('hi,{}'.format(name))

def s(request,num):
    return HttpResponse(num**2)

def l(request,num1,num2):
    
    step = -1 if num1 > num2 else 1
    result=range(num1,num2+step,step)

    # if num1<num2:
    #     result=range(num1,num2+1)
    # else :
    #     result=reversed(range(num2,num1+1))

    return render(request,'l.html',{'list':result})

templates/books/add.html
{% extends "layout.html" %}

{% load bootstrap4 %}

{% block main %}
  <div class="row">
      <div class="col">
          <h2>新增書籍</h2>
          <hr>
          <form action="" method="post">
              {% csrf_token %}
              {% bootstrap_form form %}
              <button type="submit" class="btn btn-primary float-right">Send</button>
            </form>
          <br>
          
         
      </div>
  </div>
{% endblock main %}

templates/books/delete.html
{% extends "layout.html" %}

{% load bootstrap4 %}

{% block main %}
  <div class="row">
      <div class="col">
          <h2>刪除書籍</h2>
          <hr>
          {% include "share/form.html" %}
          
         
      </div>
  </div>
{% endblock main %}

templates/books/edit.html
{% extends "layout.html" %}

{% load bootstrap4 %}

{% block main %}
  <div class="row">
      <div class="col">
          <h2>更新書籍</h2>
          <hr>
          {% include "share/form.html" %}
          
          
         
      </div>
  </div>
{% endblock main %}

templates/books/index.html
{% extends "layout.html" %}

{% block main %}
<div class="row">
    <div class="col">            
            <a href="{% url 'books:add' %}" class="btn btn-outline-info float-right">Add book</a>
            <h2>Book List</h2>
            <hr>
            <table class="table table-striped">
                
                <thead>
                    <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Price</th>
                    </tr>
                </thead>
               
                <tbody>  
                    {% for book in books %}
                        <tr>
                        <td>{{book.id}}</td>
                        <td><a href="{% url 'books:show' book.id %}">{{book.name}}</a></td>
                        <td>{{book.price}}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="3" class="text-center">no books</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
</div>
  
{% endblock main %}

templates/books/show.html
{% extends 'layout.html' %}

{% block main%}

    <h2>#{{book.id}} {{book.name}}</h2>
    <hr>
    <p>Name : {{book.name}}</p>
    <p>Price : {{book.price}}</p>
    <p>introduction : {{book.introduction | linebreaksbr}}</p>

    <a href="{% url 'books:index' %}" class="btn btn-primary">BACK</a>
    <a href="{% url 'books:edit' book.id %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'books:delete' book.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

templates/l.html
<ul>
    {% for i in list %}
    <li>{{ i }}</li>
    {% endfor %}
</ul>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Store</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>
{% load bootstrap4 %}
<body>
    <div class="container my-3">
    {% bootstrap_messages %}

    {% block main %}
      
    {% endblock main %}
    </div>
</body>
</html>

templates/share/form.html
{% load bootstrap4 %}

<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary float-right">Send</button>
    <a href="{% url 'books:index' %}" class="btn btn-primary">BACK</a>
  </form>